"""add provider review fields

Revision ID: e8f5c3d2b1a9
Revises: d1e2c7f8ea8d
Create Date: 2026-08-14 08:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision: str = 'e8f5c3d2b1a9'
down_revision: Union[str, Sequence[str], None] = 'd1e2c7f8ea8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'reviews',
        sa.Column('provider_rating', sa.Integer(), nullable=True)
    )
    op.add_column(
        'reviews',
        sa.Column('provider_comment', sa.Text(), nullable=True)
    )
    # Make rating nullable to support two-way reviews
    op.alter_column('reviews', 'rating', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'rating', existing_type=sa.Integer(), nullable=False)
    op.drop_column('reviews', 'provider_comment')
    op.drop_column('reviews', 'provider_rating')
    # ### end Alembic commands ###
